media:
  - name: files
    label: Files
    categories: [ document ]
  - name: images # Note: 'name' key is required here
    label: Images
    extensions: [ png, webp ]
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    media: images
    view:
      fields: [ title, date, tour, length ]
      sort: [ tour, title ]
      default:
        sort : tour
        order: desc
    fields:
      - { name: layout, type: string, hidden: true, default: post }
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: length, label: Length, type: number }
      - { name: up, label: Up, type: number }
      - { name: down, label: Down, type: number }
      - { name: tour, label: Tour, type: number }
      - { name: image, label: Image, type: image }
      - { name: featured_post, label: Featured Post, type: reference, options: collection: posts }
      - { name: body, label: Body, type: rich-text }


